name: Team5_BE Project CI/CD

on:
  push:
    branches: [ "Master" ]
  pull_request:
    branches: [ "Master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 전체 레포지토리 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ojosama_repo  # 상위 디렉토리 이름으로 체크아웃
      
      # Spring Boot 프로젝트 체크아웃
      - name: Checkout Spring boot Project
        uses: actions/checkout@v4
        with:
          path: ojosama_repo/Team5_BE
      # 파이썬 프로젝트 체크아웃
      - name: Checkout Python project
        uses: actions/checkout@v4
        with:
          repository: anaconda77/recommend-algorithms
          path: ojosama_repo/recommend-algorithms
          token: ${{ secrets.RECOMMEND_ALGORITHMS_PAT }}
          
      # Spring Boot 빌드
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle
          
      - name: Create Spring Boot properties
        run: |
          mkdir -p ./ojosama_repo/Team5_BE/src/main/resources
          echo "${{ secrets.APPLICATION }}" > ./ojosama_repo/Team5_BE/src/main/resources/application.properties
          echo "${{ secrets.APPLICATION_LOCAL }}" > ./ojosama_repo/Team5_BE/src/main/resources/application-local.properties
          echo "${{ secrets.APPLICATION_OAUTH }}" > ./ojosama_repo/Team5_BE/src/main/resources/application-oauth.properties
          
      - name: Build Spring Boot
        working-directory: ./ojosama_repo/Team5_BE
        run: |
          chmod +x gradlew
          ./gradlew clean build --exclude-task test
        
      # Docker 설정
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      # 배포 서버에 SSH로 접속하여 컨테이너 실행 (선택사항)
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /ojosama_repo
            sudo docker-compose up -d
